// <auto-generated />
namespace PolishGamesRanking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddRate6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRate6));
        
        string IMigrationMetadata.Id
        {
            get { return "201706161453514_AddRate6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
